### ISSUE TITLE
Rpi 4 support

### ISSUE THREAD

**Issue by lessandro-ugulino** [undistro/zora#198] opened 2023-03-06 23:11 UTC
## Question
Hi - is there any plan to make this available for  Raspberry Pi 4 as well?

## System Information
Raspberry Pi 4

**Comment by matheusfm** [comment] 2023-03-07 13:04
Hi @lessandro-ugulino 
Thank you for this issue.

Zora is made to run inside a Kubernetes cluster.

Do you run a Kubernetes cluster on Raspberry Pi?
If yes, It should work installing Zora on this cluster. The installation method would be the same.

**Comment by matheusfm** [comment] 2023-03-08 01:11
@lessandro-ugulino
Your question is related to this issue? https://github.com/undistro/zora/issues/200

**Comment by lessandro-ugulino** [comment] 2023-03-08 05:39
@matheusfm Yes, this is related.

Apologies for not sending all details.

Also, I've applied the parameters suggested but it looks like the worker image for the cronjob doesn't support ARM architecture. I created my own image by changing the file `Dockerfile.worker` to support ARM, and now it works.

**Comment by matheusfm** [comment] 2023-03-08 12:23
@lessandro-ugulino 

So I will close this issue as duplicate and we can focus the conversations on the https://github.com/undistro/zora/issues/200, ok?

Please tell us about your tests, what do you change in `Dockerfile.worker`.

**Comment by matheusfm** [comment] 2023-03-08 12:24
Duplicate of https://github.com/undistro/zora/issues/200

**Closed by matheusfm** 2023-03-08 12:24 UTC
Labels: question
